# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_opinions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='source',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(db_index=True, max_length=128, null=True, unique=True),
        ),
    ]
