# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_opinions', '0001_squashed_0004_auto_20170711_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='location',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
