# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-08 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_opinions', '0002_feedback_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=128),
            preserve_default=False,
        ),
    ]
