# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect_opinions', '0003_auto_20170710_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='source',
            new_name='source_type',
        ),
        migrations.AddField(
            model_name='feedback',
            name='source_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
