# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('get_metrics', '0001_initial'), ('get_metrics', '0002_auto_20170711_1056'), ('get_metrics', '0003_auto_20170711_1719')]

    initial = True

    dependencies = [
        ('collect_opinions', '0003_auto_20170710_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('feedback', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='collect_opinions.Feedback')),
            ],
            options={
                'verbose_name': 'Metrics',
                'verbose_name_plural': 'Metrics_list',
            },
        ),
    ]
