# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
            ],
        ),
    ]
