# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect_opinions', '0003_auto_20170710_1914'),
        ('get_metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metrics',
            options={'verbose_name': 'Metrics', 'verbose_name_plural': 'Metrics_list'},
        ),
        migrations.AddField(
            model_name='metrics',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collect_opinions.Feedback'),
        ),
    ]
