# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('get_metrics', '0002_auto_20170711_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metrics',
            name='feedback',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='collect_opinions.Feedback'),
        ),
    ]
