# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('dispatch_to_support', '0001_initial'), ('dispatch_to_support', '0002_auto_20170712_0946'), ('dispatch_to_support', '0003_auto_20170712_0947'), ('dispatch_to_support', '0004_auto_20170712_0949'), ('dispatch_to_support', '0005_auto_20170712_1213'), ('dispatch_to_support', '0006_auto_20170712_1534'), ('dispatch_to_support', '0007_supportticket_support_person'), ('dispatch_to_support', '0008_auto_20170713_1744'), ('dispatch_to_support', '0009_auto_20170713_1751'), ('dispatch_to_support', '0010_auto_20170713_1808'), ('dispatch_to_support', '0011_response')]

    initial = True

    dependencies = [
        ('collect_opinions', '0004_auto_20170711_1706'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'open'), (1, 'closed')], null=True)),
                ('opened', models.DateTimeField(blank=True, null=True)),
                ('closed', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets_issued', to='collect_opinions.Feedback')),
                ('support_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SupportTicket',
                'verbose_name_plural': 'SupportTickets',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('support_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses_given', to=settings.AUTH_USER_MODEL)),
                ('support_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses_by_support', to='dispatch_to_support.SupportTicket')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
            },
        ),
    ]
