# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collect_opinions', '0004_auto_20170711_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'open'), (1, 'close')], default=0)),
                ('opened', models.DateTimeField(null=True)),
                ('closed', models.DateTimeField(null=True)),
                ('feedback', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collect_opinions.Feedback')),
            ],
            options={
                'verbose_name': 'SupportTicket',
                'verbose_name_plural': 'SupportTickets',
            },
        ),
    ]
