# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_to_support', '0003_auto_20170712_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.IntegerField(choices=[(0, 'open'), (1, 'closed')], default=0),
        ),
    ]
