# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch_to_support', '0005_auto_20170712_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'open'), (1, 'closed')], null=True),
        ),
    ]
