# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 06:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatch_to_support', '0010_auto_20170713_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('support_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses_given', to=settings.AUTH_USER_MODEL)),
                ('support_ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses_by_support', to='dispatch_to_support.SupportTicket')),
            ],
            options={
                'verbose_name': 'Response',
                'verbose_name_plural': 'Responses',
            },
        ),
    ]
